# Generated by Django 5.2.3 on 2025-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01', help_text="Requis pour vérifier l'âge minimum de 15 ans", verbose_name='Date de naissance'),
            preserve_default=False,
        ),
    ]
