# Generated by Django 5.2.3 on 2025-07-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'issue")),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée')], default='MEDIUM', max_length=10, verbose_name='Priorité')),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Fonctionnalité'), ('TASK', 'Tâche')], default='TASK', max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('TO_DO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('FINISHED', 'Terminé')], default='TO_DO', max_length=15, verbose_name='Statut')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_issues', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_time'],
            },
        ),
    ]
